### ISSUE TITLE
Fails to run in IE11

### ISSUE THREAD

**Issue by carsonpowers** [marssantoso/initialism#3]
Causes the page to crash with
`SCRIPT1006: Expected ')'`

It's because of the default value for `length`  being provided here:
https://github.com/marssantoso/initialism/blob/499acaf760bbc9e957037fccb35b8aa6b2cd293c/lib/initials.js#L9

It's ES6 and IE doesn't understand it.

**Comment by marssantoso** [comment]
Hi. Thanks for the notice. I have pushed a (possible) fix for this.

Feel free to try the version `1.0.2`, and let me know if this works as I don't have access to IE.
